### PR TITLE
Allow using usb webcams with fswebcam

### PR DESCRIPTION
**Pull request by Polectron**
image
image

### CODE REVIEW

**Comment by OpenScanEu** [comment]
Thanks a lot!! I didn't know that webcams could be implemented such easily :)) First tests look great. Thank you again!

**Comment by Xgl0baltk** [comment]
i recieved my Arducam a while ago but haven't built my rig yet, but using a webcam is great option, haven't followed in a while, is a multicam setup an option? 1080p webcams cost next to nothing

**Comment by OpenScanEu** [comment]
The current firmware can only handle one camera at a time. And as far as I know, this is a general limitation of the RaspberryPi (at least with Pi Cameras and Arducams. Multicamera Rigs always use multiple Raspberry Pis, each controlling a single camera. (Which is a huge investment considering the current RPi prices...).

**Comment by Polectron** [comment]
I think it should be possible to make a multi-rig setup with usb cameras, as long as you don't exceed power limit of the usb ports, in theory you could be able to connect 4 usb cameras to a raspberry pi and take pictures from each device
using 4 consecutive `fsdwebcam` commands with the `--device` argument.

```
-d, --device [<prefix>:]<device name>
              Set the source or device to use. The source module is selected automatically unless
              specified in the prefix.

              Default is /dev/video0.
```
https://manpages.ubuntu.com/manpages/bionic/man1/fswebcam.1.html

**Pull request merged**
