### PR TITLE
Update flows.json - addressing issues #16, #17, #19, #24, #27

### PR DESCRIPTION
**Pull request by sokol07**
Modified flows to solve below problems:
1. Ringlight slider didn't have setting to light up all LEDs (issue #16 )
2. Problem with selected set deletion (issue #17 )
3. Updated functionality of the ringlight (issue #19 )

### CODE REVIEW

**Comment by sokol07** [comment]
There is a flaw in this update causing it to crash when booted. It needs to be updated, I'll try to fix it and commit changes.

**Comment by sokol07** [comment]
Fixed the error causing the flow to crash on startup. Should work fine now.

**Comment by yoyo42** [comment]
I've loaded this manually (just swapped the flows.json file in and rebooted). My files list now shows what I expect it to, a number of scans that had previously completed but never appeared, and some previously deleted ones have gone away. The ringlight test appears to work too, although the test slider resets to off after the first scan and it carries on being automatic. It restarted on bootup fine.

The led setting is a little strange, I get settings: off - horiz+vert LEDs lit - diagonal LEDs lit - all lit. The diagonal setting is actually slightly dimmer than the horiz+vert LEDs with the polarizer/diffuser fittted at least.

**Comment by sokol07** [comment]
What you mention about the files list surprises me - the update should only change the behaviour of the set deletion. Anyway, I'm happy it worked correctly.
The ringlight operation is correct I believe - ringlight is operated with 2 power lines, one for horiz+vert and second for diag so these are three options we are able to achieve. The only modification to the ringlight slider is addition of the last position, where all LEDs are lit.
The "ringlight test" switch resets to off after starting the scan - this is expected behaviour, this assures that when the scan is completed (or stopped) the ringlight is turned off until a new scan is started or the test is turned on manually.

**Comment by yoyo42** [comment]
I wonder if it's that the list has a max number showing - I had 8-10? on there then some new scans stopped showing up. I tried to delete some but it failed after the first couple of deletes, both individually or delete all. Then I found your version and on first loading it listed only the new ones, correctly. Either way it's working as expected now.

I recall all LEDs being lit with Openscan 1 but as I recently put the 16mp Arducam on and updated the software it's not fresh in my mind, and I've only needed half power so far so I didn't spot them not having an all-on position. They do have now.

Thanks for the fixes (and Thomas for the whole project!)

**Comment by sokol07** [comment]
I've added implementation of the pause function as described in my comment in issue #24

**Comment by sokol07** [comment]
I've added preview enable/disable switch, as requested in #27

**Pull request closed without merging**
